media: public/static
content:
  - name: microblog
    label: Microblogs
    type: collection
    path: src/content/microblogs
    filename: "mpost-{month}-{day}-{year}.md"
    commit:
      templates:
        create: "📑 content(create): New microblog -> {filename}"
        update: "📑 content(update): Update microblog #({filename})"
        delete: "📑 content(delete): Deleted microblog -> #({filename})"
        rename: "📑 content(rename): Renamed microblog {oldFilename} -> {newFilename}"
    fields:
      - name: body
        type: rich-text
        required: true
        
      - name: date
        type: date
        default: ""
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ssXXX
        
      - name: updatedDate
        type: date
        default: ""
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ssXXX
        
      - name: tags
        type: string
        list: true
        
      - name: pinned
        type: boolean
        
      