media: public/static
content:
  - name: microblog
    label: Microblogs
    type: collection
    path: src/content/microblogs
    filename: "mpost-{month}-{day}-{year}.md"
    fields:
      - name: body
        type: rich-text
        required: true
        
      - name: date
        type: date
        default: ""
        options:
          time: true
          format: "MM-dd-yy hh:mm a"
        
      - name: updatedDate
        type: date
        default: ""
        options:
          time: true
          format: "MM-dd-yy hh:mm a"
        
      - name: tags
        type: string
        list: true
        
      - name: pinned
        type: boolean
        
      